const config = require('../config');
const nvidiaService = require('./nvidiaLlmService');
const ollamaService = require('./ollamaLlmService');

// ─────────────────────────────────────────────
//  Explain Service
//  Takes SQL query results and generates a
//  natural language insight summary using LLM.
//  Called by POST /api/smart-query/explain
// ─────────────────────────────────────────────

class ExplainService {

    /**
     * Generate a natural language insight from query results.
     *
     * @param {string}   question     - Original user question
     * @param {string}   moduleCode   - MARKET or ENGINEERING
     * @param {string[]} columns      - Column names
     * @param {object[]} sampleData   - Top N rows of result data
     * @param {string}   generatedSql - The SQL that was executed
     * @param {number}   rowCount     - Total row count
     * @returns {Promise<{success: boolean, insight?: string, errorDetail?: string}>}
     */
    async generateInsight({ question, moduleCode, columns, sampleData, generatedSql, rowCount }) {
        const startTime = Date.now();

        try {
            // Limit sample data to configured max
            const maxRows = config.explain.maxSampleRows;
            const sample = (sampleData || []).slice(0, maxRows);

            // Build the explain prompt
            const systemPrompt = this._buildSystemPrompt();
            const userMessage = this._buildUserMessage({
                question, moduleCode, columns, sample, generatedSql, rowCount
            });

            console.log(`[Explain] Generating insight for: "${question.slice(0, 60)}…" (${rowCount} rows, ${columns.length} cols)`);

            // Call LLM (same NVIDIA primary + Ollama fallback pattern)
            let insight, source;
            try {
                insight = await this._callLlm(nvidiaService, systemPrompt, userMessage);
                source = 'NVIDIA NIM';
            } catch (e) {
                console.warn(`[Explain] NVIDIA failed: ${e.message}. Trying Ollama…`);
                insight = await this._callLlm(ollamaService, systemPrompt, userMessage);
                source = 'Local Ollama';
            }

            const elapsed = Date.now() - startTime;
            console.log(`[Explain] Generated by ${source} in ${elapsed}ms (${insight.length} chars)`);

            return {
                success: true,
                insight: insight.trim(),
                source,
                elapsedMs: elapsed,
            };

        } catch (e) {
            const elapsed = Date.now() - startTime;
            console.error(`[Explain] Failed after ${elapsed}ms:`, e.message);
            return {
                success: false,
                errorDetail: `Could not generate insight: ${e.message}`,
            };
        }
    }

    /**
     * Call LLM service with explain-specific parameters.
     * Uses generateText() (not generateSql()) so natural-language responses
     * are not rejected by the SQL validator.
     */
    async _callLlm(service, systemPrompt, userMessage) {
        // Use generateText() if available (NvidiaLlmService), otherwise fall back to generateSql()
        let result;
        if (typeof service.generateText === 'function') {
            result = await service.generateText(systemPrompt, userMessage);
        } else {
            result = await service.generateSql(systemPrompt, userMessage);
        }

        let cleaned = (result || '').trim();

        // Strip markdown code fences if present
        cleaned = cleaned.replace(/```[\s\S]*?```/g, '').trim();

        // Strip <think> blocks
        if (cleaned.includes('</think>')) {
            cleaned = cleaned.substring(cleaned.lastIndexOf('</think>') + 8).trim();
        }

        if (!cleaned) throw new Error('LLM returned empty insight');
        return cleaned;
    }

    _buildSystemPrompt() {
        return `You are a data analyst assistant for KMC (Kolkata Municipal Corporation) ERP system.

Your job is to analyze SQL query results and provide a clear, concise, actionable insight summary in plain English.

RULES:
1. Be concise — 2-5 sentences for the main insight, then optional bullet points for key findings.
2. Use **bold** for important numbers, names, and key findings.
3. Use bullet points (•) for listing specific findings if there are multiple.
4. Mention actual values from the data — don't be vague.
5. If there are trends (increasing/decreasing), call them out.
6. If data shows potential issues (overdue payments, anomalies), flag them.
7. End with a brief actionable suggestion if appropriate.
8. Do NOT include SQL or technical details.
9. Do NOT repeat the question — jump straight into the insight.
10. Write as if briefing a municipal officer who needs quick takeaways.`;
    }

    _buildUserMessage({ question, moduleCode, columns, sample, generatedSql, rowCount }) {
        // Format sample data as a readable table
        let dataPreview = '';
        if (sample.length > 0) {
            // Header
            dataPreview += columns.join(' | ') + '\n';
            dataPreview += columns.map(() => '---').join(' | ') + '\n';
            // Rows (max 20 for token economy)
            const displayRows = sample.slice(0, 20);
            for (const row of displayRows) {
                dataPreview += columns.map(c => {
                    const v = row[c];
                    if (v == null) return 'NULL';
                    const s = String(v);
                    return s.length > 30 ? s.slice(0, 28) + '…' : s;
                }).join(' | ') + '\n';
            }
            if (sample.length > 20) {
                dataPreview += `... and ${sample.length - 20} more rows in sample\n`;
            }
        }

        return `Analyze these query results and provide a brief insight summary.

QUESTION: ${question}
MODULE: ${moduleCode}
TOTAL ROWS: ${rowCount}
COLUMNS: ${columns.join(', ')}

DATA SAMPLE:
${dataPreview || '(no data)'}

Provide a concise insight summary with key findings and any actionable observations.`;
    }
}

module.exports = new ExplainService();
