const pool = require('../config/database');
const config = require('../config');
const { getBuilder } = require('../utils/promptBuilder');
const sqlValidator = require('../utils/sqlValidator');
const nvidiaService = require('./nvidiaLlmService');
const ollamaService = require('./ollamaLlmService');
const queryCache = require('./queryCache');
const schemaCacheService = require('./schemaCacheService');

let queryCounter = 0;

const MODULE_PREFIX = {
    MARKET:      'MKT',
    ENGINEERING: 'ENGG'
};

function generateQueryId(moduleCode) {
    const prefix = MODULE_PREFIX[moduleCode] || 'QRY';
    const today  = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    return `${prefix}-${today}-${String(++queryCounter).padStart(5, '0')}`;
}

// ─────────────────────────────────────────────
//  processQuery — standard (non-streaming)
//  Now with: cache check + follow-up context
// ─────────────────────────────────────────────
async function processQuery(request) {
    const startTime  = Date.now();
    const moduleCode = (request.moduleCode || 'MARKET').toUpperCase();
    const queryId    = generateQueryId(moduleCode);

    console.log(`[${queryId}] Module: ${moduleCode} | User: '${request.userId || 'anonymous'}' | Q: '${request.question}'`);

    try {
        // --- STEP 1: Get module-specific prompt builder ---
        let promptBuilder;
        try {
            promptBuilder = getBuilder(moduleCode);
        } catch (e) {
            return { success: false, errorType: 'INVALID_MODULE', errorDetail: `Module '${moduleCode}' is not supported. Valid: MARKET, ENGINEERING` };
        }

        // --- STEP 1b: Apply auto-discovered schema (zero-shot) ---
        if (config.schemaDiscovery.enabled) {
            try {
                const entry = await schemaCacheService.getSchema(moduleCode);
                promptBuilder.applyDiscoveredSchema(entry.schema);
            } catch (e) {
                console.warn(`[${queryId}] Schema discovery unavailable — using static schema: ${e.message}`);
            }
        }

        // --- STEP 1c: Check cache ---
        const cached = queryCache.get(request.question, moduleCode, request);
        if (cached.hit) {
            console.log(`[${queryId}] Cache HIT — skipping LLM`);
            let realSql = cached.sql;
            realSql = sqlValidator.enforceLimits(realSql, config.validation.maxRows);

            const { columns, data } = await executeQuery(realSql);
            const elapsed = Date.now() - startTime;
            console.log(`[${queryId}] Cached query — ${data.length} rows in ${elapsed}ms`);

            return {
                success: true, generatedSql: realSql, columns, data,
                rowCount: data.length, source: cached.source,
                moduleCode, executionTimeMs: elapsed, queryId, fromCache: true,
                ragStats: null
            };
        }

        // --- STEP 2: Build prompts — use RAG for targeted context ---
        const { prompt: systemPrompt, ragStats } =
            promptBuilder.buildRagSystemPrompt(request.question);
        if (ragStats) {
            console.log(`[${queryId}] RAG — intents: [${ragStats.intents.join(', ')}] | examples: ${ragStats.selectedExamples}/${ragStats.totalExamples} | tables: ${ragStats.selectedTables}/${ragStats.totalTables} | rules: ${ragStats.selectedRules}/${ragStats.totalRules} | ${ragStats.retrievalMs}ms`);
        }
        const userMessage  = promptBuilder.buildUserMessage(request.question, request);

        // --- STEP 3: Call LLM ---
        let aliasedSql, source;
        try {
            aliasedSql = await nvidiaService.generateSql(systemPrompt, userMessage);
            source     = nvidiaService.getProviderName();
        } catch (e) {
            console.warn(`[${queryId}] NVIDIA failed: ${e.message}. Trying Ollama...`);
            aliasedSql = await ollamaService.generateSql(systemPrompt, userMessage);
            source     = ollamaService.getProviderName();
        }
        console.log(`[${queryId}] Generated by ${source}`);

        if (aliasedSql.toUpperCase().includes('UNABLE_TO_GENERATE')) {
            return { success: false, errorType: 'UNABLE_TO_GENERATE', errorDetail: 'This question cannot be answered with the available data.' };
        }

        // --- STEP 4: Alias swap ---
        let realSql = promptBuilder.replaceAliasesWithReal(aliasedSql);
        console.log(`[${queryId}] Real SQL: ${realSql.substring(0, 300)}${realSql.length > 300 ? '...' : ''}`);

        // --- STEP 5: Validate ---
        const validation = sqlValidator.validate(realSql);
        if (!validation.valid) {
            return { success: false, errorType: 'VALIDATION_FAILED', errorDetail: validation.reason };
        }
        realSql = sqlValidator.enforceLimits(realSql, config.validation.maxRows);
        realSql = sqlValidator.fixPostgreCasts(realSql);

        // --- STEP 5b: Cache the generated SQL ---
        queryCache.set(request.question, moduleCode, request, { sql: realSql, source });

        // --- STEP 6: Execute ---
        const { columns, data } = await executeQuery(realSql);
        const elapsed = Date.now() - startTime;
        console.log(`[${queryId}] Success — ${data.length} rows in ${elapsed}ms`);

        return {
            success: true, generatedSql: realSql, columns, data,
            rowCount: data.length, source, moduleCode,
            executionTimeMs: elapsed, queryId, fromCache: false,
            ragStats
        };

    } catch (e) {
        const elapsed = Date.now() - startTime;
        console.error(`[${queryId}] Error after ${elapsed}ms:`, e.message);
        return { success: false, errorType: 'EXECUTION_ERROR', errorDetail: `Query failed: ${e.message}` };
    }
}

// ─────────────────────────────────────────────
//  processQueryStream — SSE streaming version
//  Emits events at each pipeline step via callback.
//  Callback signature: emit({ type, ...data })
// ─────────────────────────────────────────────
async function processQueryStreaming(request, emit) {
    const startTime  = Date.now();
    const moduleCode = (request.moduleCode || 'MARKET').toUpperCase();
    const queryId    = generateQueryId(moduleCode);

    console.log(`[${queryId}][STREAM] Module: ${moduleCode} | Q: '${request.question}'`);

    try {
        // ── STEP 1: Schema context ──
        emit({ type: 'step', step: 1, label: 'Loading schema context and few-shot examples…' });

        let promptBuilder;
        try {
            promptBuilder = getBuilder(moduleCode);
        } catch (e) {
            emit({ type: 'error', errorType: 'INVALID_MODULE', errorDetail: `Module '${moduleCode}' not supported.` });
            return;
        }

        // Apply auto-discovered schema (zero-shot)
        if (config.schemaDiscovery.enabled) {
            try {
                const entry = await schemaCacheService.getSchema(moduleCode);
                promptBuilder.applyDiscoveredSchema(entry.schema);
            } catch (e) {
                console.warn(`[${queryId}][STREAM] Schema discovery unavailable — using static schema: ${e.message}`);
            }
        }

        // Check cache
        const cached = queryCache.get(request.question, moduleCode, request);
        if (cached.hit) {
            console.log(`[${queryId}][STREAM] Cache HIT`);
            emit({ type: 'step', step: 2, label: 'Cache hit — skipping AI generation' });
            emit({ type: 'sql_done', sql: cached.sql });
            emit({ type: 'step', step: 3, label: 'SQL from cache — validation passed' });
            emit({ type: 'step', step: 4, label: 'Executing cached query on PostgreSQL…' });

            let realSql = sqlValidator.enforceLimits(cached.sql, config.validation.maxRows);
            const { columns, data } = await executeQuery(realSql);
            const elapsed = Date.now() - startTime;

            emit({
                type: 'result', success: true, generatedSql: realSql,
                columns, data, rowCount: data.length, source: cached.source,
                moduleCode, executionTimeMs: elapsed, queryId, fromCache: true,
            });
            return;
        }

        // ── STEP 2: AI Processing ──
        const isFollowUp = !!(request.previousSql && request.previousSql.trim());
        emit({ type: 'step', step: 2, label: isFollowUp ? 'Follow-up: AI modifying previous SQL…' : 'AI is generating SQL — NVIDIA NIM processing…' });

        const { prompt: systemPrompt, ragStats } =
            promptBuilder.buildRagSystemPrompt(request.question);
        if (ragStats) {
            console.log(`[${queryId}][STREAM] RAG — intents: [${ragStats.intents.join(', ')}] | examples: ${ragStats.selectedExamples}/${ragStats.totalExamples} | tables: ${ragStats.selectedTables}/${ragStats.totalTables}`);
        }
        const userMessage  = promptBuilder.buildUserMessage(request.question, request);

        let aliasedSql, source;
        try {
            // TODO: When NVIDIA supports streaming, emit sql_token events here
            aliasedSql = await nvidiaService.generateSql(systemPrompt, userMessage);
            source     = nvidiaService.getProviderName();
        } catch (e) {
            emit({ type: 'step', step: 2, label: 'NVIDIA failed, trying Ollama fallback…' });
            aliasedSql = await ollamaService.generateSql(systemPrompt, userMessage);
            source     = ollamaService.getProviderName();
        }

        if (aliasedSql.toUpperCase().includes('UNABLE_TO_GENERATE')) {
            emit({ type: 'error', errorType: 'UNABLE_TO_GENERATE', errorDetail: 'Cannot answer with available data.' });
            return;
        }

        // Send completed SQL
        let realSql = promptBuilder.replaceAliasesWithReal(aliasedSql);
        emit({ type: 'sql_done', sql: realSql });

        // ── STEP 3: Validation ──
        emit({ type: 'step', step: 3, label: 'Validating SQL — safety checks and limits…' });

        const validation = sqlValidator.validate(realSql);
        if (!validation.valid) {
            emit({ type: 'error', errorType: 'VALIDATION_FAILED', errorDetail: validation.reason });
            return;
        }
        realSql = sqlValidator.enforceLimits(realSql, config.validation.maxRows);
        realSql = sqlValidator.fixPostgreCasts(realSql);

        queryCache.set(request.question, moduleCode, request, { sql: realSql, source });

        // ── STEP 4: Execute ──
        emit({ type: 'step', step: 4, label: 'Executing query on PostgreSQL…' });

        const { columns, data } = await executeQuery(realSql);
        const elapsed = Date.now() - startTime;
        console.log(`[${queryId}][STREAM] Success — ${data.length} rows in ${elapsed}ms`);

        emit({
            type: 'result', success: true, generatedSql: realSql,
            columns, data, rowCount: data.length, source,
            moduleCode, executionTimeMs: elapsed, queryId, fromCache: false,
            ragStats
        });

    } catch (e) {
        const elapsed = Date.now() - startTime;
        console.error(`[${queryId}][STREAM] Error after ${elapsed}ms:`, e.message);
        emit({ type: 'error', errorType: 'EXECUTION_ERROR', errorDetail: e.message });
    }
}

// ─────────────────────────────────────────────
//  Execute SQL on PostgreSQL
// ─────────────────────────────────────────────
async function executeQuery(sql) {
    const client = await pool.connect();
    try {
        await client.query(`SET statement_timeout = '${config.validation.queryTimeoutSeconds}s'`);
        const result = await client.query(sql);
        return { columns: result.fields.map(f => f.name), data: result.rows };
    } finally {
        client.release();
    }
}

module.exports = { processQuery, processQueryStreaming, queryCache };
